name: cicd

on: [pull_request] 

jobs:
  
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Spin up containers
        run: make up
      - name: Run CI test
        run: make ci    



  deploy:
    needs: [run-ci-tests]
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server EC2
        uses: easingthemes/ssh-deploy@main
        env:

          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: "ec2-54-152-179-25.compute-1.amazonaws.com"
          REMOTE_USER: ${{secrets.USERNAME}}
          TARGET: ${{secrets.TARGET_DIR}}

